### ISSUE TITLE
Application crashes when deleting purchase

### ISSUE THREAD

**Issue by VMelnalksnis** [VMelnalksnis/Gnomeshade#1259]
**Describe the bug**
After clicking `Delete Selected` in purchase overview, the application crashes.

**To Reproduce**
1. Go to `Transaction overview`
2. Select a transaction with purchases
3. Select one of the purchases
4. Click `Delete Selected`
5. See that the application crashes

**Expected behavior**
The purchase is deleted.

**Additional context**
```csharp
Avalonia App terminated unexpectedly
System.InvalidCastException: Unable to cast object of type 'Gnomeshade.Avalonia.Core.Transactions.Purchases.PurchaseViewModel' to type 'Gnomeshade.Avalonia.Core.OverviewViewModel`2[Gnomeshade.Avalonia.Core.Accounts.AccountOverviewRow,Gnomeshade.Avalonia.Core.Accounts.AccountUpsertionViewModel]'.
   at CompiledAvaloniaXaml.XamlIlTrampolines.Gnomeshade.Avalonia.Core:Gnomeshade.Avalonia.Core.OverviewViewModel`2+DeleteSelectedAsync_0!CommandExecuteTrampoline(Object, Object)
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.CommandAccessorPlugin.CommandAccessor.Command.Execute(Object)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive, RoutedEventArgs)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice, UInt64, IInputRoot, Point, PointerPointProperties, KeyModifiers, IInputElement )
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr, UInt32, IntPtr, IntPtr)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[])
   at Gnomeshade.Desktop.Program.Main(String[] args)
```

**Comment by VMelnalksnis** [comment]
Similiar issue with products:
```csharp
Avalonia App terminated unexpectedly
System.InvalidCastException: Unable to cast object of type 'Gnomeshade.Avalonia.Core.Products.ProductViewModel' to type 'Gnomeshade.Avalonia.Core.OverviewViewModel`2[Gnomeshade.Avalonia.Core.Accounts.AccountOverviewRow,Gnomeshade.Avalonia.Core.Accounts.AccountUpsertionViewModel]'.
   at CompiledAvaloniaXaml.XamlIlTrampolines.Gnomeshade.Avalonia.Core:Gnomeshade.Avalonia.Core.OverviewViewModel`2+DeleteSelectedAsync_0!CommandExecuteTrampoline(Object, Object)
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.CommandAccessorPlugin.CommandAccessor.Command.Execute(Object)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive, RoutedEventArgs)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice, UInt64, IInputRoot, Point, PointerPointProperties, KeyModifiers, IInputElement )
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr, UInt32, IntPtr, IntPtr)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[])
   at Gnomeshade.Desktop.Program.Main(String[] args)
```

**Comment by VMelnalksnis** [comment]
Still relevant after latest Avalonia update in #1314
