### ISSUE TITLE
Purchase view model refresh sometimes throws and exception

### ISSUE THREAD

**Issue by VMelnalksnis** [VMelnalksnis/Gnomeshade#390]
**Describe the bug**
Sometimes when either editing purchases, or the transaction it self, `System.InvalidOperationException: Sequence contains no matching element` is thrown. When editing the transaction this causes an error message to be displayed, but the application crashes when editing purchases.

**To Reproduce**
1. Create new transaction
2. Add single purchase
3. Reconcile the transaction

```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at Gnomeshade.Interfaces.Avalonia.Core.Transactions.Purchases.PurchaseViewModel.SetDefaultCurrency() in /_/source/Gnomeshade.Interfaces.Avalonia.Core/Transactions/Purchases/PurchaseViewModel.cs:line 153
   at Gnomeshade.Interfaces.Avalonia.Core.Transactions.Purchases.PurchaseViewModel.Refresh() in /_/source/Gnomeshade.Interfaces.Avalonia.Core/Transactions/Purchases/PurchaseViewModel.cs:line 106
   at Gnomeshade.Interfaces.Avalonia.Core.ViewModelBase.RefreshAsync() in /_/source/Gnomeshade.Interfaces.Avalonia.Core/ViewModelBase.cs:line 28
   at Gnomeshade.Interfaces.Avalonia.Core.Transactions.Purchases.PurchaseViewModel.DetailsOnUpserted(Object sender, UpsertedEventArgs e) in /_/source/Gnomeshade.Interfaces.Avalonia.Core/Transactions/Purchases/PurchaseViewModel.cs:line 171
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 283
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
```

**Comment by VMelnalksnis** [comment]
Haven't encountered this bug in a while, might be fixed. Closing for now.
