### ISSUE TITLE
WebApi logs full of 'Failed to validate the token.' mesages

### ISSUE THREAD

**Issue by VMelnalksnis** [VMelnalksnis/Gnomeshade#428]
**Describe the bug**
After #427 the WebApi logs are full informational messages when OIDC authentication configuration has been added.

**Additional context**
https://github.com/VMelnalksnis/Gnomeshade/runs/7940890146?check_suite_focus=true
```
2022-08-21 18:39:56 [Information] Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10503: Signature validation failed. Token does not have a kid. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey, KeyId: 'HA9uRs7iu00npjs0EA7tWiZ4MXYoM54ARESolwzwP6k', InternalId: '1wW9yTNy5Y6ihpVac4Rh1md3cNI'. , KeyId: HA9uRs7iu00npjs0EA7tWiZ4MXYoM54ARESolwzwP6k
Microsoft.IdentityModel.Tokens.RsaSecurityKey, KeyId: 'HA9uRs7iu00npjs0EA7tWiZ4MXYoM54ARESolwzwP6k', InternalId: 'nWseokwn39GHvWa2qOpjcuPRgZTgXIkp8cmZP0Amr8k'. , KeyId: HA9uRs7iu00npjs0EA7tWiZ4MXYoM54ARESolwzwP6k
'.
Exceptions caught:
 'System.NotSupportedException: IDX10634: Unable to create the SignatureProvider.
Algorithm: 'HS256', SecurityKey: 'Microsoft.IdentityModel.Tokens.X509SecurityKey, KeyId: 'HA9uRs7iu00npjs0EA7tWiZ4MXYoM54ARESolwzwP6k', InternalId: '1wW9yTNy5Y6ihpVac4Rh1md3cNI'.'
 is not supported. The list of supported algorithms is available here: https://aka.ms/IdentityModel/supported-algorithms
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures, Boolean cacheProvider)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForVerifying(SecurityKey key, String algorithm, Boolean cacheProvider)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForVerifying(SecurityKey key, String algorithm)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
System.NotSupportedException: IDX10634: Unable to create the SignatureProvider.
Algorithm: 'HS256', SecurityKey: 'Microsoft.IdentityModel.Tokens.RsaSecurityKey, KeyId: 'HA9uRs7iu00npjs0EA7tWiZ4MXYoM54ARESolwzwP6k', InternalId: 'nWseokwn39GHvWa2qOpjcuPRgZTgXIkp8cmZP0Amr8k'.'
 is not supported. The list of supported algorithms is available here: https://aka.ms/IdentityModel/supported-algorithms
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures, Boolean cacheProvider)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForVerifying(SecurityKey key, String algorithm, Boolean cacheProvider)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForVerifying(SecurityKey key, String algorithm)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
'.
token: '{"alg":"HS256","typ":"JWT"}.{"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier":"30d6160f-8222-4c37-b7d5-6bcf65d85e5e","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name":"Kasey26","jti":"0d412294-156e-4461-b580-22518884b29f","nbf":1661107195,"exp":1661117995,"iss":"https://localhost:44320","aud":"https://localhost:44320"}'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
2022-08-21 18:39:56 [Information] "Keycloak" was not authenticated. Failure message: "IDX10503: Signature validation failed. Token does not have a kid. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey, KeyId: 'HA9uRs7iu00npjs0EA7tWiZ4MXYoM54ARESolwzwP6k', InternalId: '1wW9yTNy5Y6ihpVac4Rh1md3cNI'. , KeyId: HA9uRs7iu00npjs0EA7tWiZ4MXYoM54ARESolwzwP6k
Microsoft.IdentityModel.Tokens.RsaSecurityKey, KeyId: 'HA9uRs7iu00npjs0EA7tWiZ4MXYoM54ARESolwzwP6k', InternalId: 'nWseokwn39GHvWa2qOpjcuPRgZTgXIkp8cmZP0Amr8k'. , KeyId: HA9uRs7iu00npjs0EA7tWiZ4MXYoM54ARESolwzwP6k
'.
Exceptions caught:
 'System.NotSupportedException: IDX10634: Unable to create the SignatureProvider.
Algorithm: 'HS256', SecurityKey: 'Microsoft.IdentityModel.Tokens.X509SecurityKey, KeyId: 'HA9uRs7iu00npjs0EA7tWiZ4MXYoM54ARESolwzwP6k', InternalId: '1wW9yTNy5Y6ihpVac4Rh1md3cNI'.'
 is not supported. The list of supported algorithms is available here: https://aka.ms/IdentityModel/supported-algorithms
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures, Boolean cacheProvider)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForVerifying(SecurityKey key, String algorithm, Boolean cacheProvider)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForVerifying(SecurityKey key, String algorithm)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
System.NotSupportedException: IDX10634: Unable to create the SignatureProvider.
Algorithm: 'HS256', SecurityKey: 'Microsoft.IdentityModel.Tokens.RsaSecurityKey, KeyId: 'HA9uRs7iu00npjs0EA7tWiZ4MXYoM54ARESolwzwP6k', InternalId: 'nWseokwn39GHvWa2qOpjcuPRgZTgXIkp8cmZP0Amr8k'.'
 is not supported. The list of supported algorithms is available here: https://aka.ms/IdentityModel/supported-algorithms
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures, Boolean cacheProvider)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForVerifying(SecurityKey key, String algorithm, Boolean cacheProvider)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForVerifying(SecurityKey key, String algorithm)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
'.
token: '{\"alg\":\"HS256\",\"typ\":\"JWT\"}.{\"[http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier\](http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier/)":\"30d6160f-8222-4c37-b7d5-6bcf65d85e5e\",\"[http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name\](http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name/)":\"Kasey26\",\"jti\":\"0d412294-156e-4461-b580-22518884b29f\",\"nbf\":1661107195,\"exp\":1661117995,\"iss\":\"https://localhost:44320\",\"aud\":\"https://localhost:44320\"}'."
```

**Comment by VMelnalksnis** [comment]
This is caused by multiple authentication schemes, for example when specifying an OIDC provider and JWT options for local auth. I haven't tested with multiple OIDC providers yet, might be relevant for #451.

Most likely current auth configuration is not correct, since I mostly tried whatever until it worked.

**Comment by VMelnalksnis** [comment]
Alright, the next issue probably is here
https://github.com/VMelnalksnis/Gnomeshade/blob/f3bc3d5d33098f91e29e3fbd5050cb1d7373503e/source/Gnomeshade.WebApi/Configuration/AuthConfiguration.cs#L186
since the issuer in the JWT is `OidcProviderOptions.ServerRealm` aka `JwtBearerOptions.Authority`, at least for Keycloak. Probably need to look at some examples on how to detect the scheme from the token.
